### ISSUE TITLE
Add Personality for determining cloaking behavior

### ISSUE THREAD

**Issue by RestingImmortal** [kikotheexile/Endless-Sky-Civil-War#117]
Current cloak behavior is good for current human fighters with their poor cloaking tech, however for more advanced cloak tech and techniques (ie. Strafing runs), it would be better to have a way to determine if it gets used in such a manner or not Has been brought up by [Zitchas](https://discordapp.com/channels/615731847304839267/615748098563506207/750448403317522494) on the [Discord](https://discord.gg/ND788CC)

Currently this issue is largely as a reminder of this being something I need to implement, however if anyone else wishes to do so I will be pleased. In addition, I would love for people's ideas on this to be added to here.

**Comment by kikotheexile** [comment]
@RestingImmortal I understand you have been rather busy, and life has been hectic for all of us, but I am very excited for this change and want to remind you to work on it.

**Comment by kikotheexile** [comment]
@RestingImmortal quick bump, im also going to add some tags

**Comment by kikotheexile** [comment]
This issue is related to #125 and will be closed for the same reason: Although ship AI is very important, what we have now is good enough to finish project ESS on, and since no one wants to actually work on this for now - this will be closed with the option to reopen it later if/when AI comes back into focus.
