### ISSUE TITLE
Total conversion mod?

### ISSUE THREAD

**Issue by samrocketman** [kikotheexile/Endless-Sky-Civil-War#179]
Is this a total conversion mod?  Seems like it after reading `credits.txt`.

I plan to update upstream endless sky so that core game data can be disabled.  That would enable total conversion mods to switch to being plugins for ES instead of having to rebuild the game from scratch.

Would this be useful for your use case?

**Comment by kikotheexile** [comment]
This is not a total conversion mod, it was meant as something of a redundancy and remake in the event that the endless sky community could not continue work on the human projects. However, due to a lack of support, the project has been suspended indefinitely. 

Removing/deleting the core game data would not have helped this project at all. As most of the core game data was intended to be kept and modified - this was a stand alone project independent of the larger community.

I thank you for checking, and believe that disabling core-game-data for total conversions would be a good thing for a lot of different modders out there, but it would not have helped this project at all.

**Comment by samrocketman** [comment]
Thanks @kikotheexile for your quick response!

As an aside, the upstream project has rejuvenated so if you have any interest in contributing again I wanted to share that.

**Comment by kikotheexile** [comment]
I have no interest in contributing to the endless sky base game, nor re-opening ESS. I have moved on to other projects, and am only maintaining this repo at all in the chance that someone finds what we have done here to be useful. 

People are welcome to play it in its current, buggy, incomplete version. They are also welcome to poach anything they like from this and PR it to the Endless Sky base game if they so chose. But this was always intended to be a stand alone project.
